export interface PlatformVerifier {
    /** Platform identifier (e.g. "luogu", "codeforces") */
    platform: string;
    /** Display name for the platform */
    displayName: string;
    /** Verify user's claimed platform UID using a code and user-submitted credential */
    verify(params: VerifyParams): Promise<VerifyResult>;
}

export interface VerifyParams {
    /** The platform UID the user claims to own */
    platformUid: string;
    /** The verification code generated by the server */
    code: string;
    /** User-submitted credential (e.g. Luogu paste ID) */
    credential: string;
}

export interface VerifyResult {
    success: boolean;
    /** Confirmed platform UID */
    platformUid: string;
    /** Platform username if available */
    platformUsername?: string;
    /** Error message if verification failed */
    error?: string;
}
